# -*- coding: utf-8 -*-
"""etl_consolidado.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11acBxDKNYrT_xoi6bc9IEmRU16yPr_jG
"""

!pip install pandas pymysql
from google.colab import files
import pandas as pd
from sqlalchemy import create_engine

#Autenticación
user = "root"
password = "1234"
host = "34.10.20.53"
port = "3306"
database = "covid_db"
engine = create_engine(f"mysql+pymysql://{user}:{password}@{host}:{port}/{database}")

csv_files = ['Department.csv', 'cases.csv', 'gender.csv', 'municipality.csv', 'status.csv', 'type_contagion.csv']

print("Por favor, selecciona los archivos CSV para subir:")
uploaded = files.upload()

for filename in uploaded.keys():
  if filename in csv_files:
    print(f'Procesando {filename}...')
    try:
      df = pd.read_csv(filename, sep=';')
      df.columns = df.columns.str.replace(' ', '_').str.replace('[^A-Za-z0-9_]+', '', regex=True)
      table_name = filename.replace('.csv', '')
      df.to_sql(name=table_name, con=engine, if_exists='replace', index=False)
      print(f'Tabla "{table_name}" creada/reemplazada exitosamente en la base de datos "{database}".')
    except Exception as e:
      print(f'Error al procesar o subir el archivo {filename}: {e}')
  else:
    print(f'El archivo {filename} no está en la lista de archivos a procesar y será ignorado.')
print("Proceso completado.")

dfs = {}
for file in csv_files:
  table_name = file.replace('.csv', '')
  dfs[file] = pd.read_sql_table(table_name, engine)

# evitar nombres duplicados
dfs['gender.csv'] = dfs['gender.csv'].rename(columns={'name': 'gender_name'})
dfs['municipality.csv'] = dfs['municipality.csv'].rename(columns={'name': 'municipality_name'})
dfs['status.csv'] = dfs['status.csv'].rename(columns={'name': 'status_name'})
dfs['type_contagion.csv'] = dfs['type_contagion.csv'].rename(columns={'name': 'type_contagion_name'})
dfs['Department.csv'] = dfs['Department.csv'].rename(columns={'name': 'department_name'})


# Joins
consolidated_df = dfs['cases.csv'] \
    .merge(dfs['gender.csv'], on='id_gender', how='left') \
    .merge(dfs['municipality.csv'], on='id_municipality', how='left') \
    .merge(dfs['status.csv'], on='id_status', how='left') \
    .merge(dfs['type_contagion.csv'], on='id_type', how='left') \
    .merge(dfs['Department.csv'], on='id_department', how='left')

# subir tabla consolidada
table_name_consolidated = 'consolidada'
try:
  consolidated_df.to_sql(name=table_name_consolidated, con=engine, if_exists='replace', index=False)
  print(f'Tabla "{table_name_consolidated}" creada/reemplazada exitosamente en la base de datos "{database}".')
except Exception as e:
  print(f'Error al subir la tabla consolidada: {e}')